version: '3'
services:
  app:
    build: .
    container_name: guvi_flask
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=guvi123
      - MYSQL_DB=guvi
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=change_this_secret
      - UPLOAD_FOLDER=static/uploads
    volumes:
      - ./static/uploads:/app/static/uploads
    depends_on:
      - db
      - mongo
      - redis

  db:
    image: mysql:8
    container_name: guvi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: guvi123
      MYSQL_DATABASE: guvi
    ports:
      - "3307:3306"
    volumes:
      - guvi_mysql_data:/var/lib/mysql
      - ./init_users_table.sql:/docker-entrypoint-initdb.d/init_users_table.sql

  mongo:
    image: mongo:6
    container_name: guvi_mongo
    ports:
      - "27018:27017"
    volumes:
      - guvi_mongo_data:/data/db

  redis:
    image: redis:7
    container_name: guvi_redis
    ports:
      - "6380:6379"

volumes:
  guvi_mysql_data:
  guvi_mongo_data:
